import tkinter as tk
import word_search
import window

word_search = word_search.WordSearch(24)
word_search.add_word("hello")
word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hellqqqqqqqqqqqqqq")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hellsssssssssssssssssss")
# word_search.add_word("flipper")
# word_search.add_word("flipperrr")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
# word_search.add_word("hello")
word_search.word_list = sorted(word_search.word_list, key=len, reverse=True)
word_search.place_words()
# word_search.fill_board()
root = tk.Tk()
root.title("Word Search")
root.geometry("1280x750")
root.configure(bg="#101010")
word_search_gui = window.WordSearchGUI(root, word_search)
root.mainloop()
